# config.py
CREDENTIALS = {
    "SMARTSHEET_API_KEY": None,
    "SMARTSHEET_FOLDER_ID": None,
    "GOOGLE_DRIVE_SHEETS_FOLDER_ID": None,
    "GOOGLE_DRIVE__COMMENTS_FOLDER_ID": None,
    "GOOGLE_DRIVE_ATTACHMENTS_FOLDER_ID": None,
    "APPSHEET_API_KEY": None,
    "APPSHEET_APP_ID": None,
    "APPSHEET_TABLE_NAME": None,
}
